# Environment variables names
ARANGO_HOST = 'ARANGO_HOST'
ARANGO_USERNAME = 'ARANGO_USERNAME'
ARANGO_PASSWORD = 'ARANGO_PASSWORD'
ARANGO_DB_NAME = 'ARANGO_DB_NAME'
ARANGO_GRAPH_NAME = 'ARANGO_GRAPH_NAME'

NEO4J_HOST = 'NEO4J_HOST'
NEO4J_DB_NAME = 'NEO4J_DB_NAME'
NEO4J_BRON_USERNAME = 'NEO4J_BRON_USERNAME'
NEO4J_BRON_PASSWORD = 'NEO4J_BRON_PASSWORD'


# Arango constants
ARANGO_EDGE_DEF_TYPE_PROP = 'edge_collection'
ARANGO_EDGE_DEF_FROM_TYPE_PROP = 'from_vertex_collections'
ARANGO_EDGE_DEF_TO_TYPE_PROP = 'to_vertex_collections'

ARANGO_NODE_ID_PROP = '_id'

ARANGO_EDGE_ID_PROP = '_id'
ARANGO_EDGE_FROM_ID_PROP = '_from'
ARANGO_EDGE_TO_ID_PROP = '_to'


# File system
INSTRUCTIONS_DIR = 'instructions'
DOCUMENTS_DIR = 'documents'
INSTRUCTIONS_NODES_DIR_NAME = 'nodes'
INSTRUCTIONS_EDGES_DIR_NAME = 'edges'
GRAPHS_DIR = 'arango_graphs'
GRAPH_FILE_EXTENSION = '.json'
INSTRUCTIONS_FILE_EXTENSION = '.cypher'


# Graphs file
GRAPH_FILE_NODES_KEY = 'nodes'
GRAPH_FILE_EDGES_KEY = 'edges'


# Neo4j constants
MAX_THREADS = 100


# Embedding model
EMBEDDINGS_MODEL_ID = 'baai/bge-large-en-v1.5'
EMBEDDING_TOKEN = 'embedding'
